### PR TITLE
Fix the web backend in code and CI

### LINKED ISSUE #729: Fix CI checks for WASM target
Our command is now:
> cargo check --all-targets --all-features --target=wasm32-unknown-unknown

However, as of recent, we got `wgpu` as a feature, where it stops using the the WebGPU web-sys... we need to fix this ASAP.

### PR DESCRIPTION
**Pull request by kvark**
Fixes #729

### CODE REVIEW

File: src/backend/web.rs [hunk 1]
```diff
@@ -666,6 +689,13 @@ fn map_vertex_format(format: wgt::VertexFormat) -> web_sys::GpuVertexFormat {
         VertexFormat::Int2 => vf::Int2,
         VertexFormat::Int3 => vf::Int3,
         VertexFormat::Int4 => vf::Int4,
+        VertexFormat::Double |
+        VertexFormat::Double2 |
+        VertexFormat::Double3 |
+        VertexFormat::Double4 => {
+            // Not supported, but we don't want to panic
```
Comment (grovesNL) [inline src/backend/web.rs:696]: It seems ok to panic here unless we have a fallback path

**Review by grovesNL — APPROVED** [review]

**Comment by kvark** [comment]
bors r=grovesNL
